### ISSUE TITLE
PDF scrolling

### ISSUE THREAD

**Issue by andyrichardson** [jpablobr/simple-auto-scroll#3] opened 2016-09-18 14:11 UTC
I'm trying to use this extension to scroll sheet music while playing piano, something I think many pianists would want to do. Unfortunately, despite allowing _file://_ access to the extension, scrolling does not work inside the chrome PDF viewer. 

Would this be possible?

**Comment by Henry-E** [comment] 2017-01-09 10:21
PDF scrolling in Chrome is basically all I want to use this extension for. Did you ever figure out a solution?

**Comment by andyrichardson** [comment] 2017-01-09 14:43
Nope I did not. Just a thought - maybe uploading the pdf to Google Drive might solve the problem although I haven't tried.

**Comment by Henry-E** [comment] 2017-01-09 15:36
Tried using pdf from many different sources, including ones hosted online and by google drive. None seem to work.

**Comment by Muhamed0Hassan** [comment] 2017-05-26 18:10
PDF is never working :(

**Comment by RayBB** [comment] 2017-07-11 16:26
I spent some time researching the issue today since it has been a few years.
It seems that the issue is the PDF viewer isn't actually part of the DOM. It's just an embedded plugin.
There's no API to scroll, but there is an open issue for it [here](https://bugs.chromium.org/p/chromium/issues/detail?id=135146).

I also looked into trying to trigger a scroll or keydown event but [for security reasons](https://stackoverflow.com/questions/35143695/how-can-i-simulate-a-keypress-in-javascript), that's not possible in Chrome.

Since the pdf read is an extension itself, it could add a feature to for messages from other extensions. More info [here](https://developer.chrome.com/extensions/faq#faq-dev-11).

Also, I thought about making a bookmarklet (and found a pretty cool one [here](https://gist.github.com/lorenjohnson/a99ea9e913858a28db603f9d008a604c)) but the code from bookmarklets can't make the page scroll either.

The only quick fix I have is that you can copy the code of that bookmarklet and then right click on your pdf (in Chrome) and past the code in the console. That'll make it auto scroll. I also forked that gist above [here](https://gist.github.com/RayBB/359bb5946ac3c45e355bcf238e49a66e) so that the escape button stops and starts the scrolling.

**Comment by jpablobr** [comment] 2017-10-20 10:03
Thanks for the info, @RayBB. I'm sure people will still find it valuable. But yes, don't think I have the time at the moment to look into this. For now, I'm going to close the issue but anyone can still feel free to re-open in case there's more info. Or even better, a PR submission.

**Closed by jpablobr** 2017-10-20 10:03 UTC
